name: muco
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - python=3.9
  - pip
  - setuptools
  - wheel
  - ca-certificates
  - openssl
  - pdbfixer
  - openmm
  - pymol-open-source=2.4.0
  - fastapi
  - uvicorn
  - pydantic
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - biopython
  - numpy
  - tqdm
  - pyyaml
  - biotite
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - --find-links https://data.pyg.org/whl/torch-2.7.0+cu118.html
      - torch==2.7.0+cu118
      - torchvision==0.22.0+cu118
      - torchaudio==2.7.0+cu118
      - torch-cluster
      - torch-geometric
      - fair-esm
      - easydict
      - lightning
      - omegaconf
      - einops
      - ml-collections
      - dm-tree
      - lmdb
      - mdtraj
      - wandb
      - POT
      - geomstats
      - e3nn
